openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /example:
    get:
      summary: Example endpoint
      parameters:
        - name: apiKey1
          in: header
          description: api key 1
          required: true
          schema:
            oneOf:
              - type: string
                deprecated: true
              - type: number
        - name: apiKey2
          in: header
          description: api key 2
          required: true
          schema:
            type: string
            deprecated: true
        - name: apiKey3
          in: header
          description: api key 3
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
